# Generated by Django 4.2.29 on 2026-04-06 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "STUDENT"},
                related_name="enrolled_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
