# Generated by Django 4.2.28 on 2026-02-16 15:38

import apps.lectures.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('lecture_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.subject')),
            ],
            options={
                'db_table': 'lectures',
                'ordering': ['-lecture_date'],
            },
        ),
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('m_type', models.CharField(choices=[('TRANSCRIPT', 'Transcript'), ('NOTES', 'Notes'), ('PPT', 'PowerPoint'), ('LIVE_TRANSCRIPT', 'Live Transcript')], max_length=20)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('vector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_processed_for_rag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lectures.lecture')),
            ],
            options={
                'db_table': 'lecture_materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LectureAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to=apps.lectures.models.lecture_audio_upload_path)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='lectures.lecture')),
            ],
            options={
                'db_table': 'lecture_audio',
            },
        ),
    ]
